CREATE TABLE DBO_SAMPLE.REF_USER
(
    ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(64),
    LAST_NAME   VARCHAR(64),
    COUNTRY     VARCHAR(64),
    STREET      VARCHAR(64),
    CITY        VARCHAR(64),
    STATE       VARCHAR(64),
    ZIP_CODE    VARCHAR(64),
    CREATED_BY  VARCHAR(64)     NOT NULL,
    CREATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(64)     NOT NULL,
    MODIFIED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_DELETED  BOOLEAN   DEFAULT FALSE
);
