CREATE
USER 'SAMPLE'@'localhost' IDENTIFIED BY 'SAMPLE_PASSWORD';
CREATE
USER 'SAMPLE'@'%' IDENTIFIED BY 'SAMPLE_PASSWORD';

GRANT ALL PRIVILEGES ON *.* TO
'SAMPLE'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO
'SAMPLE'@'%' WITH GRANT OPTION;

CREATE ROLE IF NOT EXISTS 'SAMPLE_RO'@'localhost';
CREATE ROLE IF NOT EXISTS 'SAMPLE_RO'@'%';

GRANT
SELECT
ON *.* TO 'SAMPLE_RO'@'localhost';
GRANT
SELECT
ON *.* TO 'SAMPLE_RO'@'%';

FLUSH
PRIVILEGES;
